### ISSUE TITLE
Indexing doesn't work on v0.2.10

### ISSUE THREAD

**Issue by ajpetersons** [TryGhost/algolia#109]
Since `IndexFactory.setSettingsForIndex()` allows optional update, creating an Algolia index doesn't work using https://github.com/TryGhost/algolia/tree/main/packages/algolia . The process exits with this error:
```
error Error saving fragments [
  TypeError: Cannot read properties of undefined (reading 'updateSettings')
      at IndexFactory.setSettingsForIndex (node_modules/@tryghost/algolia-indexer/lib/IndexFactory.js:98:32)
      at TypeCommand.run [as _runHandler] (node_modules/@tryghost/algolia/bin/cli.js:125:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 2)
]
```

It seems that the issue is either in the signature for `setSettingsForIndex` method by requiring an object as an argument instead of boolean, or that the argument is not supplied in https://github.com/TryGhost/algolia/blob/main/packages/algolia/bin/cli.js#L125C29-L125C29

**Comment by aileen** [comment]
Thanks for reporting this! Will have a look at this soon
